### ISSUE TITLE
Structure user research

### ISSUE THREAD

**Issue by wrynearson** [developmentseed/wb-agrifood-frontend#3]
After https://github.com/developmentseed/wb-agrifood-frontend/issues/2, we should think about how to get information about the technical task leads (TTLs) user needs, either from (some of) them directly, or through the WB team.

## AC

- [x] Define user research plan
- [x] Share user research plan with WB team
- [x] Conduct TTL interviews

**Comment by heidimok** [comment]
^ For the small scope, I think the user research will be framed more as early user input where we enable the WB team to engage TTLs (not us) using the initial designs we provide and our general guidance. 

My initial thinking is that we can set up a Google form that the WB team can share with their TTLs with a specific deadline to elicit initial feedback on early designs. They can respond to questions like:
1. What is a realistic **search prompt** that you would want to see results for? (Enter one or more)
2. What results would you expect to see based on that prompt?
3. If there are many results, what categories would you want to filter that information by?
4. If you selected a result, what would happen, where would you expect to be navigated to?
5. If there are no results, what would you like to see on the screen?

Our team will not be able to:
- Help recruit specific users for input
- Conduct direct interviews for feedback in the timing we have
