### ISSUE TITLE
Refine initial designs based on feedback

### ISSUE THREAD

**Issue by wrynearson** [developmentseed/wb-agrifood-frontend#4]
Dependant on https://github.com/developmentseed/wb-agrifood-frontend/issues/2 and https://github.com/developmentseed/wb-agrifood-frontend/issues/3.

Once feedback from WB team is received, and once/while user research is conducted, designs should be refined based on:
- WB team feedback
- User feedback
- Technical scope/limitations

**Comment by heidimok** [comment]
Sharing Mockup below
https://github.com/developmentseed/wb-agrifood-frontend/assets/10764915/624d9d40-ef71-4fed-b81f-1df1b8ece967

Decisions:
- Evolving Dustin's general prototype with a very clean interface 
- Using one of the World Bank's secondary colors `006068` 
- Using text + components from Tailwind
- Not incorporating filters until after we see search results, but we can consider a toolbar on top of the message box for filters
